//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/Input/RaindropsAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @RaindropsAction: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @RaindropsAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""RaindropsAction"",
    ""maps"": [
        {
            ""name"": ""Base Action"",
            ""id"": ""525f2b96-aff7-4389-9d68-d1076aab3a00"",
            ""actions"": [
                {
                    ""name"": ""Enter Action"",
                    ""type"": ""Button"",
                    ""id"": ""9cc4d0fc-b6c9-432b-90a4-dcf208fb6c08"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Escape Action"",
                    ""type"": ""Button"",
                    ""id"": ""1bd36a5d-e85f-440f-a45d-95ecfb155d1d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""53c12633-fb89-40e7-b3ff-291e851cd4dc"",
                    ""path"": ""<Keyboard>/Enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Enter Action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6038447d-5056-4798-9493-fc65ab1eada3"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Escape Action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Base Action
        m_BaseAction = asset.FindActionMap("Base Action", throwIfNotFound: true);
        m_BaseAction_EnterAction = m_BaseAction.FindAction("Enter Action", throwIfNotFound: true);
        m_BaseAction_EscapeAction = m_BaseAction.FindAction("Escape Action", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Base Action
    private readonly InputActionMap m_BaseAction;
    private List<IBaseActionActions> m_BaseActionActionsCallbackInterfaces = new List<IBaseActionActions>();
    private readonly InputAction m_BaseAction_EnterAction;
    private readonly InputAction m_BaseAction_EscapeAction;
    public struct BaseActionActions
    {
        private @RaindropsAction m_Wrapper;
        public BaseActionActions(@RaindropsAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @EnterAction => m_Wrapper.m_BaseAction_EnterAction;
        public InputAction @EscapeAction => m_Wrapper.m_BaseAction_EscapeAction;
        public InputActionMap Get() { return m_Wrapper.m_BaseAction; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BaseActionActions set) { return set.Get(); }
        public void AddCallbacks(IBaseActionActions instance)
        {
            if (instance == null || m_Wrapper.m_BaseActionActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_BaseActionActionsCallbackInterfaces.Add(instance);
            @EnterAction.started += instance.OnEnterAction;
            @EnterAction.performed += instance.OnEnterAction;
            @EnterAction.canceled += instance.OnEnterAction;
            @EscapeAction.started += instance.OnEscapeAction;
            @EscapeAction.performed += instance.OnEscapeAction;
            @EscapeAction.canceled += instance.OnEscapeAction;
        }

        private void UnregisterCallbacks(IBaseActionActions instance)
        {
            @EnterAction.started -= instance.OnEnterAction;
            @EnterAction.performed -= instance.OnEnterAction;
            @EnterAction.canceled -= instance.OnEnterAction;
            @EscapeAction.started -= instance.OnEscapeAction;
            @EscapeAction.performed -= instance.OnEscapeAction;
            @EscapeAction.canceled -= instance.OnEscapeAction;
        }

        public void RemoveCallbacks(IBaseActionActions instance)
        {
            if (m_Wrapper.m_BaseActionActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IBaseActionActions instance)
        {
            foreach (var item in m_Wrapper.m_BaseActionActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_BaseActionActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public BaseActionActions @BaseAction => new BaseActionActions(this);
    public interface IBaseActionActions
    {
        void OnEnterAction(InputAction.CallbackContext context);
        void OnEscapeAction(InputAction.CallbackContext context);
    }
}
